
insert into airlines (Id, Airline, Abbreviation, Country) values (1, 'United Airlines', 'UAL', 'USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (2, 'US Airways', 'USAir', 'USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (3, 'Delta Airlines','Delta','USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (4, 'Southwest Airlines','Southwest','USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (5, 'American Airlines','American','USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (6, 'Northwest Airlines','Northwest','USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (7, 'Continental Airlines','Continental','USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (8, 'JetBlue Airways','JetBlue','USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (9, 'Frontier Airlines', 'Frontier', 'USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (10, 'AirTran Airways', 'AirTran', 'USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (11, 'Allegiant Air', 'Allegiant', 'USA');
insert into airlines (Id, Airline, Abbreviation, Country) values (12, 'Virgin America', 'Virgin', 'USA');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Aberdeen','APG','Phillips AAF','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Aberdeen','ABR','Municipal','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Abilene','DYS','Dyess AFB','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Abilene','ABI','Municipal','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Abingdon','VJI','Virginia Highlands','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Ada','ADT','Ada','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Adak Island','ADK','Adak Island Ns','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Adrian','ADG','Lenawee County','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Afton','AFO','Municipal','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Aiken','AIK','Municipal','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Ainsworth','ANW','Ainsworth','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Akhiok','AKK','Akhiok SPB','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Akiachak','KKI','Spb','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Akiak','AKI','Akiak','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Akron CO','AKO','Colorado Plains Regional Airport','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Akron/Canton OH','CAK','Akron/canton Regional','United States','US ');
insert into airports (City, AirportCode, AirportName, Country, CountryAbbrev  ) values ('Akron/Canton','AKC','Fulton International','United States','US ');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (1,  28, 'APG','ABR');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (1,  29, 'AIK','ADT');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (1,  44, 'AKO','AKI');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (1,  45, 'CAK','APG');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (1,  54, 'AFO','AKO');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (3,  2, 'AIK','ADT');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (3,  3, 'DYS','ABI');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (3,  26, 'AKK','VJI');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (9,  1260, 'AKO','AKC');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (9,  1261, 'APG','ABR');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (9,  1286, 'ABR','APG');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (9,  1287, 'DYS','ANW');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (10,  6, 'KKI','AKC');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (10,  7, 'VJI','APG');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (10,  54, 'ADT','APG');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (6,  4, 'AIK','AKO');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (6,  5, 'CAK','APG');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (6,  28, 'AKO','ABI');
insert into flights (Airline,  FlightNo,  SourceAirport,  DestAirport) values (6,  29, 'ABR','ABI');